### ISSUE TITLE
혹시 이 파일을 이용하여 다른 이름으로 배포해도 되나요?

### ISSUE THREAD

**Issue by Sjdnejd** [lumes-board/BoardLumesKR#1]
안녕하세요. 제가 php로 게시판을 배포해보고 싶어서 이 파일을 이용하여 배포해도 되나요?
출처는 밝히겠습니다.

**Comment by KnightChaser** [comment]
답변이 늦어서 정말 죄송합니다. 지금도 여전히 이 repository에 관심이 있으실지는 모르겠군요.
이 게시판 만드는 기간이 끝나서 방치해뒀다가 이제 확인했네요.

네, 정말 저 파일이 괜찮으시다면야... 물론 마음대로 배포하셔도 됩니다.
